import fs from "node:fs";
import path from "node:path";
import { getConfig } from "../config.js";
import { readNarrative } from "../storage/storage.js";
import type { StarNarrative, CareNarrative, NarrativeOutput } from "../types/narrative.js";

function ensureDir(dirPath: string): void {
  fs.mkdirSync(dirPath, { recursive: true });
}

export function exportMarkdown(outputPath?: string): string {
  const starData = readNarrative("star") as NarrativeOutput | null;
  const careData = readNarrative("care") as NarrativeOutput | null;

  if (!starData && !careData) {
    throw new Error("No narratives found. Run generate-narratives first.");
  }

  const date = new Date().toISOString().split("T")[0];
  const lines: string[] = [];

  lines.push("# Portfolio");
  lines.push("");
  lines.push(`> Generated by PRISM on ${date}`);
  lines.push("");
  lines.push("---");

  if (starData && starData.narratives.length > 0) {
    lines.push("");
    lines.push("## STAR Narratives");

    for (const narrative of starData.narratives as StarNarrative[]) {
      lines.push("");
      lines.push(`### ${narrative.theme}`);
      lines.push("");
      lines.push("**Situation**");
      lines.push(narrative.situation);
      lines.push("");
      lines.push("**Task**");
      lines.push(narrative.task);
      lines.push("");
      lines.push("**Action**");
      lines.push(narrative.action);
      lines.push("");
      lines.push("**Result**");
      lines.push(narrative.result);
      lines.push("");
      lines.push("---");
    }
  }

  if (careData && careData.narratives.length > 0) {
    lines.push("");
    lines.push("## CARE Narratives");

    for (const narrative of careData.narratives as CareNarrative[]) {
      lines.push("");
      lines.push(`### ${narrative.theme}`);
      lines.push("");
      lines.push("**Context**");
      lines.push(narrative.context);
      lines.push("");
      lines.push("**Action**");
      lines.push(narrative.action);
      lines.push("");
      lines.push("**Result**");
      lines.push(narrative.result);
      lines.push("");
      lines.push("**Evolution**");
      lines.push(narrative.evolution);
      lines.push("");
      lines.push("---");
    }
  }

  const filePath = outputPath ?? path.join(getConfig().DATA_DIR, "portfolio.md");
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, lines.join("\n") + "\n");

  return filePath;
}
